# 자동 생성 (23부 문구 모으기). 키 → 한국어. frag.* = 조각 (trf 가 화면 넣기 직전에 바꿈)
KO = {
    'vfo.title': 'VFO',
    'vfo.center': '중심',
    'vfo.rf': 'RF',
    'vfo.ptt': 'PTT',
    'vfo.not_connected': '연결되지 않음',
    'vfo.help': '다이얼: 자리 위 휠, 클릭하면 직접 입력\n중심: 워터폴 클릭과 연동\nRF: USB 다이얼 + 중심 · LSB 다이얼 − 중심\nPTT: 누르는 동안 켬, 소리 없음',
    'meter.level': '입력 레벨',
    'meter.snr': '추정 SNR',
    'meter.freq': '주파수 오차',
    'meter.margin': '복원 여유',
    'meter.sync_wait': '시작 동기 대기',
    'meter.sync_found': '시작 동기 검출 · {t}',
    'meter.TNG1_wait': '감지 대기',
    'meter.TNG1_found': '감지 · {t}',
    'set.page.general': '일반',
    'set.page.radio': 'Radio',
    'set.page.audio': '오디오',
    'set.page.mode': '모드',
    'set.page.display': '수신/표시',
    'set.page.macro': '매크로',
    'set.language': '언어',
    'set.lang_restart': 'TNG를 다시 시작하면 적용됩니다.',
    'layout.op': '운용',
    'layout.ana': '분석',
    'layout.all': '전체',
    'wf.speed.slow': '느림',
    'wf.speed.normal': '보통',
    'wf.speed.fast': '빠름',
    'main.vertical_16_tones_horizontal': '세로: 16음 · 가로: 시간, 1칸 160 ms\n위: 수신 · 아래: 송신\n흰 테두리: CRC 통과 기호 · 청록: 동기 음\n×: 오류정정이 고친 칸\n점선: 블록 경계, 클릭하면 블록 해부',
    'main.vertical_dbfs_solid_offset': '세로축: dBFS\n실선: 중심 · 점선: 대역 경계\n자동: 한 번 맞춤',
    'main.horizontal_frequency_vertical_time': '가로: 주파수 · 세로: 시간, 위가 최신\n클릭: 중심 변경\n자홍 점선: CRC 전\n연두: CRC 통과 · 빨강: CRC 실패\n초록 네모: 시작 동기 · 청록 네모: 끝 동기',
    'main.input_level_peak_hold': '입력 레벨: 피크 홀드 1.5 s\nSNR: 2500 Hz 기준\n주파수 오차: 시작 동기 기준\n복원 여유: SNR − 실패 한계 −6.5 dB',
    'main.top_frames_bottom_segment': '위: 프레임 · 아래: 구간 CRC\n초록: 통과 · 노랑: FEC 정정 · 빨강: 실패\n클릭: 대응 프레임 · 구간 강조',
    'main.row_select_analysis_panels': '행 선택: 분석 패널 · 패킷 해부\n구간: CRC 통과 / 전체\nFEC: 정정 비트 수\nRF: 수신 때 RF 주파수',
    'main.right_click_edit_delete': '오른쪽 클릭: 편집 · 삭제\n치환: {MYCALL} {DXCALL} {SNR}',
    'main.crc_fail_segment_waiting': '□: CRC 실패 구간 · ▍: 다음 구간 대기\n위로 스크롤: 따라가기 해제\n지우기: 화면만',
    'main.stop_send_the_current': '중지: 진행 중 구간까지 보내고 끝냄\n중지 두 번: 즉시 중단\n다시 보내기: TNG1 반복 합치기',
    'main.throughput_sent_chars_elapsed': '실효 속도: 완료 글자 ÷ 경과 시간\n흰 선: 현재 위치 · 회색: 완료 · 빨강: 송신 중',
    'main.bytes_info_bits_coded': '① 바이트 ② 정보 비트 ③ 부호 비트 ④ 송신 위치\n흐림: 송신 끝 · 빨간 선: 현재 프레임',
    'main.ber_hard_decision_fec': 'BER: hard 판정 기준\nFEC: 정정 비트 / 확인 비트\nEVM: 등화 후\nρ²: 시작 동기 정규화 상관',
    'main.last_60_packets_red': '최근 패킷 60개\n빨간 점선: 실패 한계 −6.5 dB\n가로축: UTC',
    'main.eq_channel_estimate_from': '등화: 복조 비트로 채널 역추정\n원본: 주파수 · 위상 보정만\nTNG1: 기호 확신도, 1등 칸 ÷ 2등 칸',
    'main.two_symbol_trace_green': '심볼 2개 길이 궤적\n초록: 등화 후 · 시안: 원본\nTNG1: 동기 누적 지도',
    'main.nn_features_2d_pca': 'NN 특징: 판정 직전 특징 PCA 2차원\n색: 송신 비트쌍\n위상 궤적: 선택 프레임 I/Q',
    'main.llr_bit_decision_confidence': 'LLR: 비트 판정 확신도\n분홍: 정답 0 · 파랑: 정답 1 · 회색: 정답 불명',
    'main.normalized_correlation_same_as': 'ρ²: 정규화 상관, 검출기와 같은 계산\n초록 윤곽: 문턱 이상\n○: 최대점 · +: 검출기 위치\n스냅샷: 마지막 검출 순간\nTNG1: 동기 12음 점수',
    'main.click_matching_position_in': '클릭: 모든 층의 대응 위치\n▲ 빨강: 비터비 정정 위치\nTNG1: 블록 · 기호 · 비트 · CRC · 문자',
    'main.dotted_sync_tones_dashed': '점선: 동기 톤 · 파선: 대역 경계\n초록 선: 주파수 오차\n분해능: 주파수 · 시간 동시 변경',
    'main.tng_analysis': 'TNG PKT 분석',
    'main.loading_models': '모델 불러오는 중',
    'main.live_waterfall': '실시간 워터폴',
    'main.segments': '구간 표시',
    'main.speed': '흐름',
    'main.palette': '컬러맵',
    'main.hard_ber': 'hard 판정 BER',
    'main.fec_fixed_checked': 'FEC 정정 / 확인 비트',
    'main.evm_after_eq': '등화 후 EVM',
    'main.costas_a': '코스타스 A ρ²',
    'main.residual_drift': '잔여 드리프트',
    'main.rx_packets': '수신 패킷',
    'main.success_rate': '성공률',
    'main.avg_snr': '평균 SNR',
    'main.tx': '송신',
    'main.session_stats': '세션 통계',
    'main.open_wav': 'WAV 열기',
    'main.live_rx': '실시간 수신',
    'main.loopback_rx': '루프백 수신',
    'main.export_csv': 'CSV 내보내기',
    'main.e_g_6l5tng': '',
    'main.dx_call': '상대 호출부호',
    'main.tx_now': '즉시 송신',
    'main.message': '보낼 내용',
    'main.save_wav': 'WAV 저장',
    'main.tx_level': '출력 음량',
    'main.audio_api': '오디오 API',
    'main.input': '입력 장치',
    'main.output': '출력 장치',
    'main.eq': '등화',
    'main.signal_restored_by_channel': '복조된 비트로 채널을 역추정해 되돌린 신호',
    'main.raw': '원본',
    'main.rx_signal_with_freq': '주파수·위상만 맞춘 수신 신호',
    'main.fft_spectrum': 'FFT 스펙트럼',
    'main.waterfall': '워터폴',
    'main.meters': '미터',
    'main.packet_timeline': '패킷 타임라인',
    'main.rx_log': '수신 로그',
    'main.rx': '수신',
    'main.tx_monitor': '송신 모니터',
    'main.tx_anatomy': '송신 해부',
    'main.channel_quality_stats': '채널 품질 / 통계',
    'main.trend': '추이 (최근 패킷)',
    'main.iq_constellation': 'IQ 성상도',
    'main.eye_diagram': '아이 다이어그램',
    'main.nn_features_phase_trace': 'NN 특징 / 위상 궤적',
    'main.llr_distribution': 'LLR 분포',
    'main.costas_sync_map': '코스타스 동기 맵',
    'main.16_tone_grid_tng1': '16음 격자 · TNG1',
    'main.packet_anatomy': '패킷 해부',
    'main.zoom_waterfall': '대역 확대 워터폴 (1500Hz ± 범위)',
    'main.layout': '레이아웃: {}',
    'main.tools': '도구',
    'main.layout2': '레이아웃',
    'main.detach_analysis': '분석 창 분리',
    'main.panels': '패널 보기',
    'main.log_folder': '로그 폴더',
    'main.settings': '설정',
    'main.g_cps_hz': '{:g}자/s · {} Hz',
    'main.not_used': '사용 안 함',
    'main.model_id_mismatch': '모델 식별값 불일치: ',
    'main.saved': '저장: {} · {}',
    'main.model_load_failed': '모델을 불러오지 못함: ',
    'main.tng5_model_load_failed': 'TNG5 모델을 불러오지 못함: {}: {}',
    'main.ready': '준비됨 · {} · {}',
    'main.damaged': '손상',
    'main.mode_locked_during_tx': '송신 중 모드 전환 불가',
    'main.mode': '모드: {}',
    'main.symbol_confidence_tng1': '기호 확신도 · TNG1',
    'main.sync_accumulation_tng1': '동기 누적 지도 · TNG1',
    'main.12_sync_tones_tng1': '동기 12음 · TNG1',
    'main.packet_anatomy_tng1': '패킷 해부 · TNG1',
    'main.tx_anatomy_tng1': '송신 해부 · TNG1',
    'main.no_anatomy_data': '{}: 해부 자료 없음',
    'main.offset_locked_during_tx': '송신 중 중심 주파수 변경 불가',
    'main.offset_0f_hz': '중심 주파수: {:.0f} Hz',
    'main.no_cat': 'CAT 없음',
    'main.cat_connected': 'CAT 연결',
    'main.cat_lost': 'CAT 끊김',
    'main.tx_halted': '송신 중단: {}',
    'main.tx2': '송신 중',
    'main.ptt_on': 'PTT 켬',
    'main.ptt_off': 'PTT 끔',
    'main.max_tx_time_exceeded': '최대 송신 시간 초과 {:.0f} s',
    'main.waiting': '수신 대기',
    'main.seg': '구간 -',
    'main.audio_api_query_failed': '오디오 API 조회 실패: {}',
    'main.audio_device_query_failed': '오디오 장치 조회 실패: {}',
    'main.cannot_open_input_device': '입력 장치를 열 수 없음: {}',
    'main.input_device_not_open': '입력 장치가 열려 있지 않음',
    'main.in_nbsp_nbsp_nbsp': '{} 입력 {} {}&nbsp;&nbsp;&nbsp;{} 출력 {}',
    'main.input_output': '입력: {}\n출력: {}',
    'main.save_as_wav': 'WAV로 저장',
    'main.wav_save_failed': 'WAV 저장 실패: {}',
    'main.cannot_read_wav': 'WAV 를 읽을 수 없음: {}',
    'main.decoding_0f_hz': '복조 중: {} · {} · {:.0f} Hz',
    'main.csv_export_rows': 'CSV 내보내기: {}행, {}',
    'main.rx_done': '수신 완료 · {}',
    'main.seg2': '구간 {}',
    'main.rx_tng5_confirm_first': '수신 중 · TNG5 (확정: 첫 CRC)',
    'main.seg_0_confirmed': '구간 0 확정',
    'main.rx_tng1_14_7': '수신 중 · TNG1 (블록 14.7 s 단위)',
    'main.block_0': '블록 0',
    'main.b_confirmed': ' · B 확인',
    'main.b_not_found': ' · B 미검출',
    'main.rx_tng5_length_field': '수신 중 · TNG5 (길이 필드 확인)',
    'main.rx_single_block_format': '수신 중 · 단일 블록 형식 (끝에서 한 번에 복조)',
    'main.rx_streaming_format': '수신 중 · 스트리밍 형식{}',
    'main.block_ok': '블록 {} 통과{}',
    'main.seg_confirmed_ok_fail': '구간 {} 확정 (통과 {} · 실패 {})',
    'main.decoding': '복조 중',
    'main.seg_ok': '구간 {}/{} 통과',
    'main.signal_lost': '신호 소실',
    'main.rx_stopped': '수신 중지',
    'main.message_is_empty': '보낼 텍스트가 비어 있음',
    'main.model_not_ready': '모델이 아직 준비되지 않음',
    'main.message_is_empty2': '보낼 내용이 비어 있음',
    'main.no_tng1_message_to': '다시 보낼 TNG1 송신이 없음',
    'main.invalid_chars_press_again': '문자표 밖 글자: {} · 다시 누르면 빼고 송신',
    'main.no_chars_to_send': '보낼 글자 없음',
    'main.no_output_device': '출력 장치가 없음',
    'main.playback_failed': '재생 실패: {}',
    'main.ptt_failed': 'PTT 실패: ',
    'main.stop': '중지',
    'main.tx_seg_0f_hz': '송신 중 · {} · {} · {} · {}구간 · {:.0f} Hz · 음량 {}%',
    'main.seg_done_sending': '구간 완료 {}/{} · 송신 중 {}',
    'main.near_end_cannot_stop': '끝 부분이라 중지 안 됨',
    'main.tx_stopped_bytes_seg': '송신 중지: {} / {} 바이트 · {}구간 · 남은 시간 {}',
    'main.log_folder_changed_applies': '로그 폴더 변경: 다음 실행부터 적용',
    'main.tx_halted_by_error': '오류로 송신 중단 · PTT 해제: {}: {}',
    'set.ok': '확인',
    'set.cancel': '취소',
    'set.apply': '적용',
    'set.operator': '운용자',
    'set.my_call': '내 호출부호',
    'set.display': '표시',
    'set.utc_local': 'UTC + 현지',
    'set.local': '현지',
    'set.clock': '시간',
    'set.logging': '기록',
    'set.browse': '찾아보기',
    'set.log_folder': '로그 저장 폴더',
    'set.devices': '장치',
    'set.level': '레벨',
    'set.startup': '시작',
    'set.last_mode': '마지막 모드 기억',
    'set.always_tng44': '항상 TNG44',
    'set.mode_at_start': '시작 시 모드',
    'set.rx_font_size': '수신 글자 크기',
    'set.name': '이름',
    'set.text': '내용',
    'set.add': '추가',
    'set.delete': '삭제',
    'set.new_macro': '새 매크로',
    'set.locked': '잠금: ',
    'w.updated_ago': '갱신 후 {}',
    'w.just_updated': '방금 갱신',
    'w.done': '완료',
    'w.idle': '대기',
    'w.remaining': '남은 시간 {}',
    'w.auto': '자동',
    'w.span_style_color_rx': '<span style="color:{}">━ 수신</span>&nbsp;&nbsp;<span style="color:{}">━ 송신</span>&nbsp;&nbsp;<span style="color:{}">┈ 피크 홀드</span>',
    'w.peak_hold': '피크 홀드',
    'w.frequency_hz': '주파수 [Hz]',
    'w.time_s': '시간 [s]',
    'w.elapsed_s': '경과 [s]',
    'w.time_ms': '시간 [ms]',
    'w.add_macro': '매크로 추가',
    'w.edit': '편집',
    'w.no_constellation_data': '성상도 자료 없음 ({})',
    'w.symbol': '심볼',
    'w.smooth': '부드럽게',
    'w.waiting_for_input': '입력 대기',
    'w.release': '해제',
    'w.time_s_0_now': '시간 [s, 0 = 지금]',
    'w.freq_error_hz': '주파수 오차 [Hz]',
    'w.time_s_0_detected': '시간 [s, 0 = 검출된 A]',
    'w.snapshot_det_2f_map': '스냅샷 {} · ρ² 검출 {:.2f} / 맵 {:.2f} · {:+.3f} s · {:+.1f} Hz',
    'w.detector_3f_fine_grid': '검출기 ρ² {:.3f} (정밀 격자)\n같은 위치 재측정 ρ² {:.3f}\n맵 격자: 2 ms · {:.2f} Hz, 최대 ρ² {:.3f}\n검출 칸 ρ² {:.3f}',
    'w.2f_above_threshold_3f': 'ρ² {:.2f} · 문턱 초과 · {:+.3f} s · {:+.1f} Hz',
    'w.max_2f_threshold_2f': '최대 ρ² {:.2f} · 문턱 {:.2f}',
    'w.bits': '비트 수',
    'w.all': '전체 분포',
    'w.hard_errors_2': 'hard 판정 오류 {} / {} ({:.2%})',
    'w.no_feature_data': '특징 자료 없음',
    'w.cluster_accuracy_0': '군집 분류 정확도 {:.0%}',
    'w.decode_failed': '복조 실패',
    'w.frame_eq_i_q': '프레임 {} 등화 I/Q 궤적',
    'qso.follow': '따라가기',
    'qso.a': '가−',
    'qso.a2': '가',
    'qso.a3': '가+',
    'qso.smaller': '글자 작게',
    'qso.default_size': '기본 크기',
    'qso.larger': '글자 크게',
    'qso.copy': '복사',
    'qso.clear': '지우기',
    'qso.rx_first_crc_ok': '수신 중 · {} (첫 CRC 통과)',
    'qso.rx_first_crc_ok2': '수신 중 (첫 CRC 통과)',
    'qso.remaining': '남은 시간 —',
    'qso.resend': '다시 보내기',
    'qso.halt': '즉시 중단',
    'qso.remaining2': '남은 시간 {} · {}{}',
    'qso.tx_idle': '송신 대기',
    'qso.amplitude': '진폭',
    'qso.data_frame': '데이터 프레임 번호',
    'qso.prev': '이전',
    'qso.next': '다음',
    'qso.follow_tx': '송신 따라가기',
    'qso.1f_cps_0f_bps': '{:.1f} 자/s · {:.0f} bps (완료 {}자)',
    'qso.1f_cps_0f_bps2': '{:.1f} 자/s · {:.0f} bps',
    'zoom.span': '범위',
    'zoom.resolution': '분해능',
    't1.time_s_0_now': '시간 [s] (0 = 지금)',
    't1.tone': ' · 음',
    't1.no_input': '입력 없음',
    't1.1st_2nd_cell_db': '1등 ÷ 2등 칸 [dB]',
    't1.block_phase_s': '블록 주기 위상 [s]',
    't1.freq_offset_hz': '주파수 오프셋 [Hz]',
    't1.blocks_max_1f_threshold': '누적 {} 블록 · 최대 {:.1f} · 문턱 {:.1f}',
    't1.symbol_in_block': '블록 안 기호 번호',
    't1.tone2': '음',
    't1.12_sync_tone_score': '{} · 동기 12음 점수 [dB] · 합 {:.1f} dB',
    't1.block': '블록',
    't1.block_b_start_2f': '번호 B{} · 시작 {:.2f} s · 주파수 {:+.2f} Hz · 길이 14.72 s (동기 12 + 데이터 80 기호)\nCRC16 시작값 {} ({}) · {}',
    't1.92_symbols_s_sync': '기호 92개 (S = 동기, 숫자 = 최종 음, 괄호 = 에너지 1등이 다른 칸)',
    't1.strongest_cell_final_80': '에너지 1등 칸 ≠ 최종: {} / 80 데이터 기호 (비터비가 고친 자리)',
    't1.viterbi_bits_64_text': '비터비 비트 (문자 64 + CRC16)',
    't1.received_computed': '받은 값 = 계산 값 {} → {}',
    't1.ok': '통과',
    't1.variable_length_text_decode': '가변 길이 문자 풀기 (57자 Huffman)',
    't1.eot_end_of_message': 'EOT (메시지 끝)',
    't1.text': '글자: ',
    't1.tng1_packet': 'TNG1 패킷',
    't1.no_crc_ok_block': 'CRC 통과 블록 없음',
    't1.b_chars': 'B{} · {}자',
    't1.tng1_tx_chars_blocks': 'TNG1 송신 · {}자 · {} 블록 · {:.1f} s',
    't1.text_variable_length_bits': '문자 → 가변 길이 비트 (57자 Huffman)',
    't1.block_text_64_bits': '블록 문자 64 비트 + CRC16',
    't1.crc16_init': '\nCRC16 시작값 {} ({})',
    't1.coding_tail_biting_convolutional': '부호화: 테일바이팅 컨볼루션 K=13 R1/4 (가지 출력 4비트 = 16음 기호 1개) → 블록 안 인터리버',
    't1.92_16_tone_symbols': '16음 기호 92개 (동기 12 = S, 처프 50 Hz 위로, 160 ms)',
    'w.detach_attach': '분리 · 붙이기',
    'w.close': '닫기',
    'w.min': '하한',
    'w.max': '상한',
    'w.frame': '프레임',
    'w.seg': '구간',
    'w.crc16_ok': 'CRC16 통과',
    'w.crc16_fail': 'CRC16 실패',
    'w.pending': '대기 (미확정)',
    'w.sent': '송신 완료',
    'w.seg_bytes_bits_in': '구간 {}  (바이트 {}–{})  {}\n비트가 실린 프레임 {}개: F{}–F{}\n클릭: 해당 프레임 강조',
    'w.ok': '정상',
    'w.fec_fixed': 'FEC 정정',
    'w.fail': '실패',
    'w.unknown_fail_segment_bits': '정답 불명 (실패 구간 비트)',
    'w.frame_fixed_bits_mean': '프레임 {}  {}\n정정 비트  {}\n평균 |LLR| {}{}\n클릭: 분석 패널 프레임 선택',
    'w.segments': '\n실린 구간 {}',
    'w.lead_tone_300_ms': '희생 톤 300 ms (송수신 전환 · AGC 안정)',
    'w.costas_array_224_ms': '코스타스 배열 224 ms',
    'w.guard_frame_tx_ramp': '가드 프레임 (송신 램프 구간)',
    'w.costas_b_not_found': '코스타스 B 미검출',
    'w.fec_bits': 'FEC 비트',
    'w.result': '결과',
    'w.partial': '부분',
    'w.ok2': '성공',
    'w.margin': '여유',
    'w.message': '메시지',
    'w.macro_name': '매크로 이름',
    'w.macro_text': '매크로 내용',
    'w.mycall_dxcall_snr_allowed': '{MYCALL} {DXCALL} {SNR} 을 쓸 수 있다',
    'w.evm_1f_db_before': 'EVM {:.1f} dB (등화 전 {:.1f} dB)',
    'w.residual_drift_2f_hz': '잔여 드리프트 {:+.2f} Hz',
    'w.no_eq_decode_failed': '등화 불가 (복조 실패) · 원본 표시',
    'w.no_phase_reference_old': '위상 기준 없음 (옛 형식)',
    'w.frame_highlighted': '프레임 {} 강조',
    'w.live': '실시간',
    'w.last_1_5_s': '최근 1.5 s (0 = 지금)',
    'w.snapshot': '스냅샷',
    'w.detection_snapshot_map_at': '검출 스냅샷: 마지막 코스타스 A 검출 순간의 맵 (0 = 검출된 창)',
    'w.nn_features': 'NN 특징',
    'w.2d_pca_of_rx': '수신 NN 판정 직전 특징의 PCA 2차원',
    'w.phase_trace': '위상 궤적',
    'w.eq_i_q_trace': '선택 프레임의 등화 I/Q 궤적',
    'qso.stop_first_bytes': ' · 중지: 앞 {} / {} 바이트',
    'qso.tx_stage': '송신 단계',
    'qso.current_seg': '현재 구간',
    'qso.elapsed': '경과 시간',
    'qso.remaining3': '남은 시간',
    'qso.throughput_data': '실효 속도 데이터',
    'qso.throughput_total': '실효 속도 전체',
    'qso.seg_text': '구간 글자',
    'qso.seg_bytes': '구간 바이트',
    'qso.chars_in_sent_segments': '송신 완료 구간의 글자 수 ÷ 첫 데이터 프레임 시작 뒤 경과 시간\n구간이 다 나가야 셈',
    'qso.chars_in_sent_segments2': '송신 완료 구간의 글자 수 ÷ 송신 시작(무음 · 톤 · 코스타스 A 포함) 뒤 경과 시간',
    'qso.bytes_32_seg_2': '① 바이트 (구간 32 + CRC16 2)',
    'qso.info_bits': '② 정보 비트',
    'qso.convolutional_code_bits_k': '③ 컨볼루션 부호 비트 (K=7, R=1/2)',
    'qso.tx_position_after_interleaving': '④ 인터리빙 뒤 송신 위치',
    'qso.lead_silence': '시작 무음',
    'qso.tone_300_ms': '톤 (300 ms)',
    'qso.start_sync_welch12_costas': '시작 동기 (Welch12 코스타스)',
    'qso.guard_frame_start': '가드 프레임 (시작)',
    'qso.mid_sync_m': '중간 동기 M{}',
    'qso.data_frame2': '데이터 프레임 {} / {}',
    'qso.guard_frame_end': '가드 프레임 (끝)',
    'qso.costas_b_0_34': '코스타스 B (0.34 s)',
    'qso.tail_silence': '끝 무음',
    'qso.costas_a': '코스타스 A',
    'qso.costas_b': '코스타스 B',
    'qso.sending_done': '송신 중 {} / {} (완료 {})',
    'qso.none_seg_sent': '없음 · {}구간 송신 완료',
    'qso.idle_seg_total': '대기 · 전체 {}구간',
    'qso.stop_up_to_seg': ' · 중지: 구간 {}까지',
    'qso.length_b': '(길이 {} B) ',
    'qso.drift': '드리프트',
    'qso.resync': '재탐색',
    'qso.message_reason': '메시지 · 사유',
    't1.first_block': '메시지 첫 블록',
    't1.next_block': '이어지는 블록',
    't1.combined_x': '반복 합치기 {}회 결합',
    't1.single_decode': '단독 복호',
    't1.14_padding_partial_code': '{:<14} 채움 (미완성 부호, 버림)',
    't1.no_rx_packet': '수신 패킷 없음',
    't1.x_combined': ' · {}회 결합',
    't1.padding_bits_1': '채움 {} 비트 (1)',
    'frag.encode_bytes_differs_from': 'encode_bytes 가 encode_stream 과 다르다',
    'frag.block_of_a_past': '이미 지나간 송신의 블록이 뒤늦게 반복 합치기로 풀림',
    'frag.tng5_start_sync_welch': 'TNG5 시작 동기 Welch 12차 코스타스',
    'frag.per_segment_18_bytes': '구간마다 18바이트 + CRC16 + 꼬리 6',
    'frag.turns_confirmed_when_a': '블록 CRC16 통과 때 확정 칸으로 바뀌고',
    'frag.stop_message_does_not': '중지 메시지가 이미 나간 프레임과 어긋난다',
    'frag.per_segment_160_tail': '구간마다 160 + 꼬리 6 + 빈 2',
    'frag.tng5_message_end_from': 'TNG5 길이 필드로 메시지 끝 확인',
    'frag.same_band_inside_a': '끝낸 확정 메시지 구간 안 같은 대역',
    'frag.install_hamlib_or_set': 'Hamlib 설치 또는 경로 지정',
    'frag.m_join_hypothesis_passed': 'M 합류 가설이 먼저 CRC 통과',
    'frag.charset1_57_chars_variable': 'charset1 57자 가변 길이',
    'frag.bytes_18_crc16_2': '① 바이트 18 + CRC16 2',
    'frag.generators_117_127_155': '생성 117 127 155 171',
    'frag.code_bits_after_deinterleaving': '컨볼루션 디인터리빙 후 부호 비트',
    'frag.corrections_on_checkable_bits': '확인 가능한 비트 기준 정정 여부',
    'frag.ptt_release_sent_on': '다시 연결되면 PTT 해제 명령',
    'frag.12_sync_80_data': '동기 12 + 데이터 80 심볼',
    'frag.not_found_within_expected': '예상 끝 + 2 s 안에 미검출',
    'frag.deinterleave_combine_4_repeats': '디인터리빙 + 반복 4회 결합',
    'frag.updated_on_each_block': '블록 CRC16 통과마다 갱신',
    'frag.tone_300_ms_costas': '톤 300ms + 코스타스 A',
    'frag.same_band_inside_a2': '확정 수신 구간 안 같은 대역',
    'frag.crc16_per_18_byte': '18바이트 구간별 CRC16',
    'frag.mid_sync_m_every': '20프레임마다 중간 동기 M',
    'frag.crc16_per_32_byte': '32바이트 구간별 CRC16',
    'frag.tng5_costas_a_not': 'TNG5 코스타스 A 미검출',
    'frag.tng5_costas_b_1': 'TNG5 코스타스 B × 1',
    'frag.segment_end_48_info': '구간 끝 + 48 정보 비트',
    'frag.final_decode_after_b': 'B 뒤 최종 복조는 끝까지',
    'frag.tng5_mid_sync_not': 'TNG5 중간 동기 미검출',
    'frag.tng5_costas_b_ignored': 'TNG5 코스타스 B 무시',
    'frag.tng5_costas_b_confirmed': 'TNG5 코스타스 B 확인',
    'frag.charset1_variable_length': 'charset1 가변 길이',
    'frag.length_field_costas_b': '길이 필드 + 코스타스 B',
    'frag.switched_to_pending_a': '대기 중이던 A 로 갈아탐',
    'frag.full_range_after_2': '연속 2 실패 시 전 범위',
    'frag.for_large_or_dual': '큰 화면이나 듀얼 모니터용',
    'frag.one_crc16_for_the': '패킷 전체 CRC16 1개',
    'frag.removed_quietly_if_not': '확인 안 되면 조용히 지움',
    'frag.664_bits_4_repeats': '664비트 × 4회 반복',
    'frag.ptt_method_cat_unavailable': 'PTT 방식 CAT 불가',
    'frag.tng5_message_end_detected': 'TNG5 메시지 끝 감지',
    'frag.link7_streaming_v2': 'link7 스트리밍 v2',
    'frag.rigctld_start_failed': 'rigctld 실행 실패',
    'frag.rigctld_connection_lost': 'rigctld 연결 끊김',
    'frag.rigctld_connect_failed': 'rigctld 접속 실패',
    'frag.code_bit_tx_position': '④ 부호 비트 송신 위치',
    'frag.guard_frame_192_ms': '가드 프레임 192 ms',
    'frag.random_within_segment_delay': '구간 안 무작위 + 지연',
    'frag.accepted_after_length_field': '길이 필드 결과 뒤 인정',
    'frag.replaced_by_final_result': '끝나면 최종 결과로 바뀜',
    'frag.switched_to_stronger_new': '더 센 새 A 로 갈아탐',
    'frag.code_bits_after_deinterleaving2': '디인터리빙 후 부호 비트',
    'frag.start_sync_welch12': '시작 동기 Welch12',
    'frag.mid_sync_check_had': '중간 동기 확인 실패였음',
    'frag.costas_a_224_ms': '코스타스 A 224 ms',
    'frag.costas_b_224_ms': '코스타스 B 224 ms',
    'frag.ptt_port_open_failed': 'PTT 포트 열기 실패',
    'frag.tng1_block_rx': 'TNG1 블록 수신 중',
    'frag.tng5_mid_sync_m': 'TNG5 중간 동기 M',
    'frag.length_field_not_decoded': '길이 필드 복원 안 됨',
    'frag.viterbi_output_info_bits': '비터비 출력 정보 비트',
    'frag.bits_in_frames_f': '비트가 실린 프레임 F',
    'frag.not_opened_as_new': '새 메시지로 열지 않음',
    'frag.rx_nn_output_llr': '수신 NN 출력 LLR',
    'frag.interleaver_about_9_6': '인터리버 약 9.6 s',
    'frag.mid_sync_remeasure_failed': '중간 동기 재측정 실패',
    'frag.4_codewords_664_bits': '4 부호어 664비트',
    'frag.frequency_differs_from_a': 'A 와 주파수 불일치',
    'frag.crc16_fail_segment': 'CRC16 실패 구간',
    'frag.tng5_unconfirmed_dropped': 'TNG5 미확정 폐기',
    'frag.tng5_costas_b': 'TNG5 코스타스 B',
    'frag.tng5_not_enough_frames': 'TNG5 프레임 부족',
    'frag.rigctld_exited': 'rigctld 종료됨',
    'frag.mean_per_repeat_copy': '③ 반복 사본별 평균',
    'frag.not_at_segment_boundary': '구간 경계 자리 아님',
    'frag.from_length_field_end': '길이 필드 예상 끝과',
    'frag.top_sync_accumulation_candidate': '동기 누적 1위 후보',
    'frag.sum_of_4_copy': '사본 4개 LLR 합',
    'frag.grid_of_message_in': '수신 중 메시지 격자',
    'frag.searching_back': '을 되짚어 찾는 중…',
    'frag.interleaver_3_2_s': '인터리버 ±3.2 s',
    'frag.mid_sync_m1_confirmed': '중간 동기 M1 확인',
    'frag.waiting_for_mid_sync': '중간 동기 확인 대기',
    'frag.mid_sync_check_failed': '중간 동기 확인 실패',
    'frag.max_tx_time_exceeded': '최대 송신 시간 초과',
    'frag.max_shift_3_2': '최대 이동 3.2 s',
    'frag.lead_tone_300_ms': '희생 톤 300 ms',
    'frag.5_combine_4_repeats': '5 반복 4회 결합',
    'frag.7_segment_crc16': '7 구간 CRC16',
    'frag.7_costas_array': '7차 코스타스 배열',
    'frag.cat_not_connected': 'CAT 연결 안 됨',
    'frag.tng1_rx_error': 'TNG1 수신 오류',
    'frag.tng5_v1_file': 'TNG5 v1 파일',
    'frag.tng5_message_end': 'TNG5 메시지 끝',
    'frag.tng5_rx_error': 'TNG5 수신 오류',
    'frag.tng5_rx_confirmed': 'TNG5 수신 확정',
    'frag.tng5_signal_detected': 'TNG5 신호 감지',
    'frag.tng5_signal_lost': 'TNG5 신호 소실',
    'frag.tng5_packet_anatomy': 'TNG5 패킷 해부',
    'frag.tng5_join_failed': 'TNG5 합류 실패',
    'frag.hard_errors': 'hard 판정 오류',
    'frag.rigctld_not_found': 'rigctld 없음',
    'frag.whole_chars_per_segment': '구간마다 글자 단위',
    'frag.false_b_in_data': '데이터 속 가짜 B',
    'frag.eot_in_last_segment': '마지막 구간 EOT',
    'frag.decode_received_part': '받은 부분까지 복조',
    'frag.differs_from_strongest': '에너지 1등과 다름',
    'frag.mid_sync_gaps_included': '중간 동기 틈 포함',
    'frag.confirmed_by_first_crc': '첫 CRC 로 확정',
    'frag.up_to_about_9': '최대 약 9.6 s',
    'frag.costas_a_false_detect': '코스타스 A 오검출',
    'frag.costas_b_backward': '코스타스 B 역방향',
    'frag.clock_drift_estimate': '클럭 드리프트 추정',
    'frag.error_bits_per_frame': '프레임별 오류 비트',
    'frag.every_3_84_s': '3.84 s 마다',
    'frag.signal_continues_after_b': 'B 뒤 신호 계속',
    'frag.crc_ok_blocks': 'CRC 통과 블록',
    'frag.no_crc_ok': 'CRC 통과 없음',
    'frag.ptt_button_pressed': 'PTT 버튼 누름',
    'frag.ptt_released_automatically': 'PTT 자동 해제',
    'frag.ptt_test': 'PTT 테스트 중',
    'frag.no_ptt_port': 'PTT 포트 없음',
    'frag.first_2_bytes_of': 'S1 앞 2바이트',
    'frag.tng1_rx': 'TNG1 수신 중',
    'frag.tng1_streaming': 'TNG1 스트리밍',
    'frag.seg_not_received': '구간 수신 못 함',
    'frag.mean_per_repeat_copy2': '반복 사본별 평균',
    'frag.no_live_confirm': '실시간 확정 없음',
    'frag.no_backward_decode': '역방향 복원 없음',
    'frag.tx_halted_by_error': '오류로 송신 중단',
    'frag.expert_panels_hidden': '전문가 패널 숨김',
    'frag.corrected_code_bits': '정정된 부호 비트',
    'frag.costas_b_confirmed': '코스타스 B 확인',
    'frag.2_byte_value_v': '2바이트 값 v',
    'frag.crc16_fail': 'CRC16 실패',
    'frag.crc16_ok': 'CRC16 통과',
    'frag.m1_check_failed': 'M1 확인 실패',
    'frag.combined_code_bits': '결합 부호 비트',
    'frag.using_default_device': '기본 장치 사용',
    'frag.from_length_field_end2': '길이 필드 끝과',
    'frag.rest_padded_with_1': '나머지 1 채움',
    'frag.next_signal_started': '다음 신호 시작',
    'frag.single_block_format': '단일 블록 형식',
    'frag.to_pending_a': '대기 중 A 로',
    'frag.outside_data': '데이터 구간 외',
    'frag.message_rx': '메시지 수신 중',
    'frag.some_blocks_failed': '블록 일부 실패',
    'frag.tx_stop_done': '송신 중지 완료',
    'frag.tx_halted': '송신 즉시 중단',
    'frag.rx_message_table': '수신 메시지 표',
    'frag.rx_raw_waveform': '수신 원본 파형',
    'frag.message_in_rx': '수신 중 메시지',
    'frag.rx_confirm_path': '수신 확정 경로',
    'frag.start_sync_score': '시작 동기 점수',
    'frag.saved_device_missing': '저장 장치 없음',
    'frag.corrected_code_bits2': '정정 부호 비트',
    'frag.traceback_48': '제한 깊이 48',
    'frag.after_freq_correction': '주파수 보정 후',
    'frag.mid_sync_join': '중간 동기 합류',
    'frag.delay_unit_24': '지연 단위 24',
    'frag.first_crc_rescue': '첫 CRC 구제',
    'frag.no_first_crc': '첫 CRC 없음',
    'frag.first_crc_ok': '첫 CRC 통과',
    'frag.max_length_exceeded': '최대 길이 초과',
    'frag.costas_a_b': '코스타스 A+B',
    'frag.costas_a_4': '코스타스 A×4',
    'frag.select_a_packet': '패킷 선택 대기',
    'frag.frame_count_fixed': '프레임 수 확정',
    'frag.no_anatomy_data': '해부 자료 없음',
    'frag.not_shown': '화면 표시 없음',
    'frag.5_deinterleave': '5 디인터리빙',
    'frag.tng1_detected': 'TNG1 감지',
    'frag.tng1_block': 'TNG1 블록',
    'frag.tng1_tx': 'TNG1 송신',
    'frag.tng1_signal': 'TNG1 신호',
    'frag.tng5_seg': 'TNG5 구간',
    'frag.char_codes': '② 글자 부호',
    'frag.r1_per_segment': '구간마다 R1',
    'frag.end_chars_cut': '끝 글자 잘림',
    'frag.no_end_mark': '끝 표식 없음',
    'frag.data_frame': '데이터 프레임',
    'frag.missed_seg': '못 받은 구간',
    'frag.byte_whitening': '바이트 흰색화',
    'frag.code_bits': '부호 비트 수',
    'frag.shape_d': '소리 모양 D',
    'frag.streaming_format': '스트리밍 형식',
    'frag.start_missed': '앞부분 미수신',
    'frag.info_bits': '정보 비트 수',
    'frag.mid_sync_m': '중간 동기 M',
    'frag.before_first_crc': '첫 CRC 전',
    'frag.first_mid_sync': '첫 중간 동기',
    'frag.click_a_layer': '층 클릭 대기',
    'frag.errors_per_frame': '프레임별 오류',
    'frag.mean_per_frame': '프레임별 평균',
    'frag.tentative_display': '확정 전 표시',
    'frag.2_baseband': '2 기저대역',
    'frag.2656_bits': '2656비트',
    'frag.agc_settle': 'AGC 안정',
    'frag.a_b_interval': 'A~B 간격',
    'frag.cat_lost': 'CAT 끊김',
    'frag.no_cat': 'CAT 없음',
    'frag.crc_fail': 'CRC 실패',
    'frag.no_crc': 'CRC 없음',
    'frag.crc_ok': 'CRC 통과',
    'frag.ptt_failed': 'PTT 실패',
    'frag.18_samples': '±18 샘플',
    'frag.interleaver': '④ 인터리버',
    'frag.computed_crc': '계산 CRC',
    'frag.baseband_i': '기저대역 I',
    'frag.resend': '다시 보내기',
    'frag.unconfirmed_signal': '미확인 신호',
    'frag.codeword_order': '부호어 순서',
    'frag.viterbi_input': '비터비 입력',
    'frag.t_r_switch': '송수신 전환',
    'frag.tx_monitor': '송신 모니터',
    'frag.false_detect_dropped': '오검출 폐기',
    'frag.all_bytes': '전체 바이트',
    'frag.freq_error': '주파수 오차',
    'frag.sorted_by_delay': '지연순 정렬',
    'frag.snr_est': '추정 SNR',
    'frag.costas_a': '코스타스 A',
    'frag.costas_b': '코스타스 B',
    'frag.white_border': '테두리 흰색',
    'frag.not_shown2': '표시 안 함',
    'frag.1_audio': '1 오디오',
    'frag.20_frames': '20프레임',
    'frag.stages_4_6': '4~6단계',
    'frag.6_viterbi': '6 비터비',
    'frag.8_bytes': '8 바이트',
    'frag.a_not_found': 'A 미검출',
    'frag.b_not_found': 'B 미검출',
    'frag.b_only': 'B만 검출',
    'frag.m1_confirmed': 'M1 확인',
    'frag.v1_file': 'v1 파일',
    'frag.branch_12': '가지 12',
    'frag.decision_depth': '결정 깊이',
    'frag.seg_decoded': '구간 복원',
    'frag.length_field': '길이 필드',
    'frag.late_combine': '늦은 결합',
    'frag.next_signal': '다음 신호',
    'frag.single_block': '단일 블록',
    'frag.message_end': '메시지 끝',
    'frag.nothing_decoded': '복원 없음',
    'frag.decode_ok': '복조 성공',
    'frag.decode_failed': '복조 실패',
    'frag.decoding': '복조 중…',
    'frag.partial': '부분 복원',
    'frag.code_bits2': '부호 비트',
    'frag.block_ok': '블록 통과',
    'frag.per_copy': '사본 기준',
    'frag.selected_packet': '선택 패킷',
    'frag.tx_order': '송신 순서',
    'frag.tx_start': '송신 시작',
    'frag.tx_done': '송신 완료',
    'frag.tx_position': '송신 위치',
    'frag.tx_halted2': '송신 중단',
    'frag.tx_focus': '송신 중심',
    'frag.tx_stopped': '송신 중지',
    'frag.tx_anatomy': '송신 해부',
    'frag.stopped': '수동 중지',
    'frag.rx_log': '수신 로그',
    'frag.rx_confirmed': '수신 확정',
    'frag.start_sync': '시작 동기',
    'frag.signal_lost': '신호 소실',
    'frag.complete': '완전 복원',
    'frag.no_response': '응답 없음',
    'frag.no_data': '자료 없음',
    'frag.relock': '잠금 복구',
    'frag.no_device': '장치 없음',
    'frag.show_all': '전부 표시',
    'frag.connect_failed': '접속 실패',
    'frag.alignment_hypothesis': '정렬 가설',
    'frag.info_bits2': '정보 비트',
    'frag.fixed_bits': '정정 비트',
    'frag.mid_sync': '중간 동기',
    'frag.max_level': '최대 레벨',
    'frag.final_decision': '최종 판단',
    'frag.track_4': '추적 ±4',
    'frag.file_decode': '파일 복조',
    'frag.no_packet': '패킷 없음',
    'frag.frame_f': '프레임 F',
    'frag.frame_color': '프레임 색',
    'frag.format_mark': '형식 표지',
    'frag.checkable': '확인 가능',
    'frag.waiting_for_check': '확인 대기',
    'frag.check_failed': '확인 실패',
    'frag.check_ok': '확인 통과',
    'frag.candidate_dropped': '후보 버림',
    'frag.failed': "' 실패",
    'frag.hex': '16진수',
    'frag.3_seg': '3 구간',
    'frag.8_chars': '8 글자',
    'frag.no_a': 'A 없음',
    'frag.b_missing': 'B 누락',
    'frag.no_b': 'B 없음',
    'frag.s_off': 's 차이',
    'frag.computed': '≠ 계산',
    'frag.code': '③ 부호',
    'frag.after_combining': '결합 후',
    'frag.seg_s': '구간 S',
    'frag.chars': '글자 수',
    'frag.tail_6': '꼬리 6',
    'frag.end_mark': '끝 표식',
    'frag.sync_z': '동기 z',
    'frag.sync_map': '동기 맵',
    'frag.sync_cells': '동기 칸',
    'frag.drift': '드리프트',
    'frag.only_detected': '만 감지',
    'frag.repeat_4': '반복 4',
    'frag.bits': '비트 수',
    'frag.selected_layer': '선택 층',
    'frag.tx': '송신 중',
    'frag.rx': '수신 중',
    'frag.streaming': '스트리밍',
    'frag.interleaver2': '인터리버',
    'frag.info_cells': '정보 칸',
    'frag.to_start': '처음으로',
    'frag.tone_start': '톤 시작',
    'frag.x_combined': '회 결합',
    'frag.hex2': '16진',
    'frag.19': '19개',
    'frag.3_chars': '3글자',
    'frag.7_stages': '7단계',
    'frag.after_a': 'A 뒤',
    'frag.data': '데이터',
    'frag.macro': '매크로',
    'frag.not_found': '미검출',
    'frag.unconfirmed': '미확인',
    'frag.pending': '미확정',
    'frag.bytes': '바이트',
    'frag.constellation': '성상도',
    'frag.live': '실시간',
    'frag.backward': '역방향',
    'frag.connected': '연결됨',
    'frag.audio': '오디오',
    'frag.waterfall': '워터폴',
    'frag.reuse': '재사용',
    'frag.resync': '재탐색',
    'frag.exited': '종료됨',
    'frag.freq': '주파수',
    'frag.reset': '초기화',
    'frag.text': '텍스트',
    'frag.frame': '프레임',
    'frag.guard': '가드',
    'frag.virtual': '가상',
    'frag.detected': '감지',
    'frag.each': '개씩',
    'frag.detected2': '검출',
    'frag.result': '결과',
    'frag.combined': '결합',
    'frag.path': '경로',
    'frag.computed2': '계산',
    'frag.seg': '구간',
    'frag.chars2': '글자',
    'frag.ref': '기준',
    'frag.symbol': '기호',
    'frag.length': '길이',
    'frag.text2': '내용',
    'frag.slow': '느림',
    'frag.next': '다음',
    'frag.similarity': '닮음',
    'frag.waiting': '대기',
    'frag.sync': '동기',
    'frag.registered': '등록',
    'frag.mode': '모드',
    'frag.unknown': '모름',
    'frag.group': '묶음',
    'frag.threshold': '문턱',
    'frag.normal': '보통',
    'frag.decode': '복조',
    'frag.body': '본문',
    'frag.code2': '부호',
    'frag.analysis': '분석',
    'frag.block': '블록',
    'frag.bits2': '비트',
    'frag.fast': '빠름',
    'frag.copy': '사본',
    'frag.state': '상태',
    'frag.select': '선택',
    'frag.ok': '성공',
    'frag.lost': '소실',
    'frag.tx2': '송신',
    'frag.rx2': '수신',
    'frag.time': '시각',
    'frag.time2': '시간',
    'frag.start': '시작',
    'frag.fail': '실패',
    'frag.eye': '아이',
    'frag.none': '없음',
    'frag.error': '오류',
    'frag.operate': '운용',
    'frag.position': '위치',
    'frag.prev': '이전',
    'frag.after': '이후',
    'frag.general': '일반',
    'frag.input': '입력',
    'frag.all': '전체',
    'frag.alignment': '정렬',
    'frag.fixed': '정정',
    'frag.kind': '종류',
    'frag.stop': '중지',
    'frag.teal': '청록',
    'frag.trend': '추이',
    'frag.output': '출력',
    'frag.code3': '코드',
    'frag.ok2': '통과',
    'frag.file': '파일',
    'frag.padding': '패딩',
    'frag.packet': '패킷',
    'frag.mean': '평균',
    'frag.display': '표시',
    'frag.join': '합류',
    'frag.item': '항목',
    'frag.format': '형식',
    'frag.confirmed': '확정',
    'frag.value': '값',
    'frag.x': '개',
    'frag.x2': '건',
    'frag.first': '앞',
    'frag.chars3': '자',
    'frag.layer': '층',
    'frag.tone': '톤',
    'frag.x3': '회',
    'main.error_prefix': '오류: ',
    'main.local_suffix': ' 현지',
    'zoom.res.시간 우선 (4Hz)': '시간 우선 (4Hz)',
    'zoom.res.균형 (2Hz)': '균형 (2Hz)',
    'zoom.res.주파수 우선 (1Hz)': '주파수 우선 (1Hz)',
    'dis.prev': '이전',
    'dis.next': '다음',
    'dis.to_start': '처음으로',
    'dis5.col.seg': '구간',
    'dis5.col.chars': '글자',
    'dis5.col.frames': '프레임',
    'dis5.col.llr': '평균 \\',
    'dis5.col.fixed': '정정',
    'dis5.col.hex': '바이트 (16진)',
    'dis5.col.text': '내용',
    'setup.title': '초기 설정',
    'setup.step.lang': '언어',
    'setup.step.call': '호출부호',
    'setup.step.audio': '오디오',
    'setup.step.radio': '무전기',
    'setup.step.diag': '진단',
    'setup.step.done': '완료',
    'setup.hint.lang': '설정에서 언제든지 변경할 수 있습니다.',
    'setup.hint.call': '이 호출부호는 매크로의 {MYCALL} 자리에 적용됩니다.',
    'setup.hint.audio': '무전기 오디오에 연결된 입력 장치와 출력 장치를 선택하십시오.',
    'setup.hint.radio': '무전기를 연결하지 않으려면 건너뛰십시오. 나중에 설정의 Radio 탭에서 연결할 수 있습니다.',
    'setup.hint.diag': '이 PC의 CPU와 오디오 장치가 TNG PKT 실행에 적합한지 점검합니다. 약 30초가 소요됩니다.',
    'setup.hint.done': '설정이 완료되었습니다. [시작]을 누르면 TNG PKT를 실행합니다.',
    'setup.prev': '이전',
    'setup.next': '다음',
    'setup.skip': '건너뛰기',
    'setup.finish': '시작',
    'setup.test_tone': '시험음',
    'setup.call': '내 호출부호',
    'diag.title': '진단',
    'diag.run': '진단 시작',
    'diag.running': '점검 중',
    'diag.none': '결과 없음',
    'diag.cpu': 'CPU',
    'diag.cpu_error': '점검 오류: {}',
    'diag.cpu_margin': '처리 여유 {:.1f}배 · 코어 1개 기준 {:.1f}배',
    'diag.no_open': '장치 연결 실패: {}',
    'diag.fs': '{:.0f} Hz',
    'diag.xrun': '버퍼 끊김 {}회',
    'diag.ppm': '클럭 오차 {:+.0f} ppm (±{:.0f})',
    'diag.ok': '적합',
    'diag.warn': '주의',
    'diag.bad': '부적합',
    'diag.time': '점검 시각: {}',
    'diag.failed': '진단을 완료하지 못했습니다: {}',
    'set.setup_group': '초기 설정',
    'set.rerun_setup': '초기 설정 다시 하기',
    'set.rerun_diag': '진단 다시 하기',
    'macro.reply': '응답',
    'macro.report': '리포트',
    'diag.step.start': '점검 준비',
    'diag.step.audio': '오디오 장치 점검',
    'diag.step.load': '수신 모델 준비',
    'diag.step.mode': '{} 수신 처리 점검',
    'diag.step.mode1': '{} 수신 처리 점검 (코어 1개 기준)',
    'diag.step.done': '점검 완료',
    'diag.cpu_margin1': '처리 여유 {:.1f}배 (코어 1개 기준)',
}
