"""English UI strings. Keys match strings_ko."""
EN = {
    'vfo.title': 'VFO',
    'vfo.center': 'Offset',
    'vfo.rf': 'RF',
    'vfo.ptt': 'PTT',
    'vfo.not_connected': 'Not connected',
    'vfo.help': 'Dial: wheel over a digit, click to type\nOffset: follows waterfall click\nRF: USB dial + offset · LSB dial − offset\nPTT: on while pressed, no audio',
    'meter.level': 'Input Level',
    'meter.snr': 'SNR Est',
    'meter.freq': 'Freq Error',
    'meter.margin': 'Margin',
    'meter.sync_wait': 'Waiting for Start Sync',
    'meter.sync_found': 'Start Sync · {t}',
    'meter.TNG1_wait': 'Waiting for detection',
    'meter.TNG1_found': 'Detected · {t}',
    'set.page.general': 'General',
    'set.page.radio': 'Radio',
    'set.page.audio': 'Audio',
    'set.page.mode': 'Mode',
    'set.page.display': 'RX / Display',
    'set.page.macro': 'Macros',
    'set.language': 'Language',
    'set.lang_restart': 'Changes take effect after TNG PKT restarts.',
    'layout.op': 'Operate',
    'layout.ana': 'Analysis',
    'layout.all': 'All',
    'wf.speed.slow': 'Slow',
    'wf.speed.normal': 'Normal',
    'wf.speed.fast': 'Fast',
    'main.vertical_16_tones_horizontal': 'Vertical: 16 tones · Horizontal: time, 1 cell 160 ms\nTop: RX · Bottom: TX\nWhite border: CRC OK symbol · Teal: sync tone\n×: cell fixed by FEC\nDotted: block boundary, click for block anatomy',
    'main.vertical_dbfs_solid_offset': 'Vertical: dBFS\nSolid: offset · Dotted: band edge\nAuto: fit once',
    'main.horizontal_frequency_vertical_time': 'Horizontal: frequency · Vertical: time, newest on top\nClick: set offset\nMagenta dotted: before CRC\nGreen: CRC OK · Red: CRC fail\nGreen box: start sync · Teal box: end sync',
    'main.input_level_peak_hold': 'Input level: peak hold 1.5 s\nSNR: 2500 Hz bandwidth\nFreq error: from start sync\nMargin: SNR − fail limit −6.5 dB',
    'main.top_frames_bottom_segment': 'Top: frames · Bottom: segment CRC\nGreen: OK · Yellow: FEC fixed · Red: fail\nClick: highlight matching frames · segments',
    'main.row_select_analysis_panels': 'Row select: analysis panels · packet anatomy\nSeg: CRC OK / total\nFEC: corrected bits\nRF: RF frequency at RX',
    'main.right_click_edit_delete': 'Right click: edit · delete\nMacros: {MYCALL} {DXCALL} {SNR}',
    'main.crc_fail_segment_waiting': '□: CRC fail segment · ▍: waiting for next segment\nScroll up: stop follow\nClear: screen only',
    'main.stop_send_the_current': 'Stop: send the current segment, then end\nStop twice: halt now\nResend: TNG1 repeat combining',
    'main.throughput_sent_chars_elapsed': 'Throughput: sent chars ÷ elapsed time\nWhite line: now · Gray: sent · Red: sending',
    'main.bytes_info_bits_coded': '① Bytes ② Info bits ③ Coded bits ④ TX position\nDim: sent · Red line: current frame',
    'main.ber_hard_decision_fec': 'BER: hard decision\nFEC: corrected bits / checked bits\nEVM: after EQ\nρ²: start sync normalized correlation',
    'main.last_60_packets_red': 'Last 60 packets\nRed dotted: fail limit −6.5 dB\nHorizontal: UTC',
    'main.eq_channel_estimate_from': 'EQ: channel estimate from decoded bits\nRaw: freq · phase correction only\nTNG1: symbol confidence, 1st cell ÷ 2nd cell',
    'main.two_symbol_trace_green': 'Two-symbol trace\nGreen: after EQ · Cyan: raw\nTNG1: sync accumulation map',
    'main.nn_features_2d_pca': 'NN features: 2D PCA before decision\nColor: TX bit pair\nPhase trace: selected frame I/Q',
    'main.llr_bit_decision_confidence': 'LLR: bit decision confidence\nPink: true 0 · Blue: true 1 · Gray: unknown',
    'main.normalized_correlation_same_as': 'ρ²: normalized correlation, same as detector\nGreen contour: above threshold\n○: peak · +: detector position\nSnapshot: last detection\nTNG1: 12 sync tone score',
    'main.click_matching_position_in': 'Click: matching position in all layers\n▲ Red: Viterbi corrections\nTNG1: block · symbols · bits · CRC · text',
    'main.dotted_sync_tones_dashed': 'Dotted: sync tones · Dashed: band edge\nGreen line: freq error\nResolution: frequency and time together',
    'main.tng_analysis': 'TNG PKT Analysis',
    'main.loading_models': 'Loading models',
    'main.live_waterfall': 'Live Waterfall',
    'main.segments': 'Segments',
    'main.speed': 'Speed',
    'main.palette': 'Palette',
    'main.hard_ber': 'Hard BER',
    'main.fec_fixed_checked': 'FEC Fixed / Checked',
    'main.evm_after_eq': 'EVM after EQ',
    'main.costas_a': 'Costas A ρ²',
    'main.residual_drift': 'Residual Drift',
    'main.rx_packets': 'RX Packets',
    'main.success_rate': 'Success Rate',
    'main.avg_snr': 'Avg SNR',
    'main.tx': 'TX',
    'main.session_stats': 'Session Stats',
    'main.open_wav': 'Open WAV',
    'main.live_rx': 'Live RX',
    'main.loopback_rx': 'Loopback RX',
    'main.export_csv': 'Export CSV',
    'main.e_g_6l5tng': '',
    'main.dx_call': 'DX Call',
    'main.tx_now': 'TX Now',
    'main.message': 'Message',
    'main.save_wav': 'Save WAV',
    'main.tx_level': 'TX Level',
    'main.audio_api': 'Audio API',
    'main.input': 'Input',
    'main.output': 'Output',
    'main.eq': 'EQ',
    'main.signal_restored_by_channel': 'Signal restored by channel estimate from decoded bits',
    'main.raw': 'Raw',
    'main.rx_signal_with_freq': 'RX signal with freq and phase correction only',
    'main.fft_spectrum': 'FFT Spectrum',
    'main.waterfall': 'Waterfall',
    'main.meters': 'Meters',
    'main.packet_timeline': 'Packet Timeline',
    'main.rx_log': 'RX Log',
    'main.rx': 'RX',
    'main.tx_monitor': 'TX Monitor',
    'main.tx_anatomy': 'TX Anatomy',
    'main.channel_quality_stats': 'Channel Quality / Stats',
    'main.trend': 'Trend',
    'main.iq_constellation': 'IQ Constellation',
    'main.eye_diagram': 'Eye Diagram',
    'main.nn_features_phase_trace': 'NN Features / Phase Trace',
    'main.llr_distribution': 'LLR Distribution',
    'main.costas_sync_map': 'Costas Sync Map',
    'main.16_tone_grid_tng1': '16-Tone Grid · TNG1',
    'main.packet_anatomy': 'Packet Anatomy',
    'main.zoom_waterfall': 'Zoom Waterfall',
    'main.layout': 'Layout: {}',
    'main.tools': 'Tools',
    'main.layout2': 'Layout',
    'main.detach_analysis': 'Detach Analysis',
    'main.panels': 'Panels',
    'main.log_folder': 'Log Folder',
    'main.settings': 'Settings',
    'main.g_cps_hz': '{:g} cps · {} Hz',
    'main.not_used': 'Not used',
    'main.model_id_mismatch': 'Model ID mismatch: ',
    'main.saved': 'Saved: {} · {}',
    'main.model_load_failed': 'Model load failed: ',
    'main.tng5_model_load_failed': 'TNG5 model load failed: {}: {}',
    'main.ready': 'Ready · {} · {}',
    'main.damaged': 'damaged',
    'main.mode_locked_during_tx': 'Mode locked during TX',
    'main.mode': 'Mode: {}',
    'main.symbol_confidence_tng1': 'Symbol Confidence · TNG1',
    'main.sync_accumulation_tng1': 'Sync Accumulation · TNG1',
    'main.12_sync_tones_tng1': '12 Sync Tones · TNG1',
    'main.packet_anatomy_tng1': 'Packet Anatomy · TNG1',
    'main.tx_anatomy_tng1': 'TX Anatomy · TNG1',
    'main.no_anatomy_data': '{}: no anatomy data',
    'main.offset_locked_during_tx': 'Offset locked during TX',
    'main.offset_0f_hz': 'Offset: {:.0f} Hz',
    'main.no_cat': 'No CAT',
    'main.cat_connected': 'CAT connected',
    'main.cat_lost': 'CAT lost',
    'main.tx_halted': 'TX halted: {}',
    'main.tx2': 'TX',
    'main.ptt_on': 'PTT on',
    'main.ptt_off': 'PTT off',
    'main.max_tx_time_exceeded': 'Max TX time exceeded {:.0f} s',
    'main.waiting': 'Waiting',
    'main.seg': 'Seg -',
    'main.audio_api_query_failed': 'Audio API query failed: {}',
    'main.audio_device_query_failed': 'Audio device query failed: {}',
    'main.cannot_open_input_device': 'Cannot open input device: {}',
    'main.input_device_not_open': 'Input device not open',
    'main.in_nbsp_nbsp_nbsp': '{} In {} {}&nbsp;&nbsp;&nbsp;{} Out {}',
    'main.input_output': 'Input: {}\nOutput: {}',
    'main.save_as_wav': 'Save as WAV',
    'main.wav_save_failed': 'WAV save failed: {}',
    'main.cannot_read_wav': 'Cannot read WAV: {}',
    'main.decoding_0f_hz': 'Decoding: {} · {} · {:.0f} Hz',
    'main.csv_export_rows': 'CSV export: {} rows, {}',
    'main.rx_done': 'RX done · {}',
    'main.seg2': 'Seg {}',
    'main.rx_tng5_confirm_first': 'RX · TNG5 (confirm: first CRC)',
    'main.seg_0_confirmed': 'Seg 0 confirmed',
    'main.rx_tng1_14_7': 'RX · TNG1 (14.7 s blocks)',
    'main.block_0': 'Block 0',
    'main.b_confirmed': ' · B confirmed',
    'main.b_not_found': ' · B not found',
    'main.rx_tng5_length_field': 'RX · TNG5 (length field)',
    'main.rx_single_block_format': 'RX · single block format (decode at end)',
    'main.rx_streaming_format': 'RX · streaming format{}',
    'main.block_ok': 'Block {} OK{}',
    'main.seg_confirmed_ok_fail': 'Seg {} confirmed (OK {} · fail {})',
    'main.decoding': 'Decoding',
    'main.seg_ok': 'Seg {}/{} OK',
    'main.signal_lost': 'Signal lost',
    'main.rx_stopped': 'RX stopped',
    'main.message_is_empty': 'Message is empty',
    'main.model_not_ready': 'Model not ready',
    'main.message_is_empty2': 'Message is empty',
    'main.no_tng1_message_to': 'No TNG1 message to resend',
    'main.invalid_chars_press_again': 'Invalid chars: {} · press again to send without them',
    'main.no_chars_to_send': 'No chars to send',
    'main.no_output_device': 'No output device',
    'main.playback_failed': 'Playback failed: {}',
    'main.ptt_failed': 'PTT failed: ',
    'main.stop': 'Stop',
    'main.tx_seg_0f_hz': 'TX · {} · {} · {} · {} seg · {:.0f} Hz · level {}%',
    'main.seg_done_sending': 'Seg done {}/{} · sending {}',
    'main.near_end_cannot_stop': 'Near end, cannot stop',
    'main.tx_stopped_bytes_seg': 'TX stopped: {} / {} bytes · {} seg · remaining {}',
    'main.log_folder_changed_applies': 'Log folder changed: applies on next start',
    'main.tx_halted_by_error': 'TX halted by error · PTT off: {}: {}',
    'set.ok': 'OK',
    'set.cancel': 'Cancel',
    'set.apply': 'Apply',
    'set.operator': 'Operator',
    'set.my_call': 'My Call',
    'set.display': 'Display',
    'set.utc_local': 'UTC + Local',
    'set.local': 'Local',
    'set.clock': 'Clock',
    'set.logging': 'Logging',
    'set.browse': 'Browse',
    'set.log_folder': 'Log Folder',
    'set.devices': 'Devices',
    'set.level': 'Level',
    'set.startup': 'Startup',
    'set.last_mode': 'Last Mode',
    'set.always_tng44': 'Always TNG44',
    'set.mode_at_start': 'Mode at Start',
    'set.rx_font_size': 'RX Font Size',
    'set.name': 'Name',
    'set.text': 'Text',
    'set.add': 'Add',
    'set.delete': 'Delete',
    'set.new_macro': 'New Macro',
    'set.locked': 'Locked: ',
    'w.updated_ago': 'Updated {} ago',
    'w.just_updated': 'Just updated',
    'w.done': 'Done',
    'w.idle': 'Idle',
    'w.remaining': 'Remaining {}',
    'w.auto': 'Auto',
    'w.span_style_color_rx': '<span style="color:{}">━ RX</span>&nbsp;&nbsp;<span style="color:{}">━ TX</span>&nbsp;&nbsp;<span style="color:{}">┈ Peak Hold</span>',
    'w.peak_hold': 'Peak Hold',
    'w.frequency_hz': 'Frequency [Hz]',
    'w.time_s': 'Time [s]',
    'w.elapsed_s': 'Elapsed [s]',
    'w.time_ms': 'Time [ms]',
    'w.add_macro': 'Add Macro',
    'w.edit': 'Edit',
    'w.no_constellation_data': 'No constellation data ({})',
    'w.symbol': 'Symbol',
    'w.smooth': 'Smooth',
    'w.waiting_for_input': 'No input',
    'w.release': 'Release',
    'w.time_s_0_now': 'Time [s, 0 = now]',
    'w.freq_error_hz': 'Freq Error [Hz]',
    'w.time_s_0_detected': 'Time [s, 0 = detected A]',
    'w.snapshot_det_2f_map': 'Snapshot {} · ρ² det {:.2f} / map {:.2f} · {:+.3f} s · {:+.1f} Hz',
    'w.detector_3f_fine_grid': 'Detector ρ² {:.3f} (fine grid)\nRemeasured ρ² {:.3f}\nMap grid: 2 ms · {:.2f} Hz, max ρ² {:.3f}\nDetected cell ρ² {:.3f}',
    'w.2f_above_threshold_3f': 'ρ² {:.2f} · above threshold · {:+.3f} s · {:+.1f} Hz',
    'w.max_2f_threshold_2f': 'Max ρ² {:.2f} · threshold {:.2f}',
    'w.bits': 'Bits',
    'w.all': 'All',
    'w.hard_errors_2': 'Hard errors {} / {} ({:.2%})',
    'w.no_feature_data': 'No feature data',
    'w.cluster_accuracy_0': 'Cluster accuracy {:.0%}',
    'w.decode_failed': 'Decode failed',
    'w.frame_eq_i_q': 'Frame {} EQ I/Q trace',
    'qso.follow': 'Follow',
    'qso.a': 'A−',
    'qso.a2': 'A',
    'qso.a3': 'A+',
    'qso.smaller': 'Smaller',
    'qso.default_size': 'Default Size',
    'qso.larger': 'Larger',
    'qso.copy': 'Copy',
    'qso.clear': 'Clear',
    'qso.rx_first_crc_ok': 'RX · {} (first CRC OK)',
    'qso.rx_first_crc_ok2': 'RX (first CRC OK)',
    'qso.remaining': 'Remaining —',
    'qso.resend': 'Resend',
    'qso.halt': 'Halt',
    'qso.remaining2': 'Remaining {} · {}{}',
    'qso.tx_idle': 'TX idle',
    'qso.amplitude': 'Amplitude',
    'qso.data_frame': 'Data Frame',
    'qso.prev': 'Prev',
    'qso.next': 'Next',
    'qso.follow_tx': 'Follow TX',
    'qso.1f_cps_0f_bps': '{:.1f} cps · {:.0f} bps (sent {} chars)',
    'qso.1f_cps_0f_bps2': '{:.1f} cps · {:.0f} bps',
    'zoom.span': 'Span',
    'zoom.resolution': 'Resolution',
    't1.time_s_0_now': 'Time [s] (0 = now)',
    't1.tone': ' · Tone',
    't1.no_input': 'No input',
    't1.1st_2nd_cell_db': '1st ÷ 2nd Cell [dB]',
    't1.block_phase_s': 'Block Phase [s]',
    't1.freq_offset_hz': 'Freq Offset [Hz]',
    't1.blocks_max_1f_threshold': '{} blocks · max {:.1f} · threshold {:.1f}',
    't1.symbol_in_block': 'Symbol in Block',
    't1.tone2': 'Tone',
    't1.12_sync_tone_score': '{} · 12 sync tone score [dB] · sum {:.1f} dB',
    't1.block': 'Block',
    't1.block_b_start_2f': 'Block B{} · start {:.2f} s · freq {:+.2f} Hz · length 14.72 s (12 sync + 80 data symbols)\nCRC16 init {} ({}) · {}',
    't1.92_symbols_s_sync': '92 symbols (S = sync, number = final tone, parentheses = strongest cell differs)',
    't1.strongest_cell_final_80': 'Strongest cell ≠ final: {} / 80 data symbols (fixed by Viterbi)',
    't1.viterbi_bits_64_text': 'Viterbi bits (64 text + CRC16)',
    't1.received_computed': 'Received = computed {} → {}',
    't1.ok': 'OK',
    't1.variable_length_text_decode': 'Variable length text decode (57-char Huffman)',
    't1.eot_end_of_message': 'EOT (end of message)',
    't1.text': 'Text: ',
    't1.tng1_packet': 'TNG1 Packet',
    't1.no_crc_ok_block': 'No CRC OK block',
    't1.b_chars': 'B{} · {} chars',
    't1.tng1_tx_chars_blocks': 'TNG1 TX · {} chars · {} blocks · {:.1f} s',
    't1.text_variable_length_bits': 'Text → variable length bits (57-char Huffman)',
    't1.block_text_64_bits': 'Block text 64 bits + CRC16',
    't1.crc16_init': '\nCRC16 init {} ({})',
    't1.coding_tail_biting_convolutional': 'Coding: tail-biting convolutional K=13 R1/4 (4 bits per branch = one 16-tone symbol) → in-block interleaver',
    't1.92_16_tone_symbols': '92 16-tone symbols (12 sync = S, chirp 50 Hz up, 160 ms)',
    'w.detach_attach': 'Detach · Attach',
    'w.close': 'Close',
    'w.min': 'Min',
    'w.max': 'Max',
    'w.frame': 'Frame',
    'w.seg': 'Seg',
    'w.crc16_ok': 'CRC16 OK',
    'w.crc16_fail': 'CRC16 fail',
    'w.pending': 'Pending',
    'w.sent': 'Sent',
    'w.seg_bytes_bits_in': 'Seg {}  (bytes {}–{})  {}\nBits in {} frames: F{}–F{}\nClick: highlight frames',
    'w.ok': 'OK',
    'w.fec_fixed': 'FEC fixed',
    'w.fail': 'Fail',
    'w.unknown_fail_segment_bits': 'Unknown (fail segment bits)',
    'w.frame_fixed_bits_mean': 'Frame {}  {}\nFixed bits  {}\nMean |LLR| {}{}\nClick: select frame in analysis panels',
    'w.segments': '\nSegments {}',
    'w.lead_tone_300_ms': 'Lead tone 300 ms (T/R switch · AGC settle)',
    'w.costas_array_224_ms': 'Costas array 224 ms',
    'w.guard_frame_tx_ramp': 'Guard frame (TX ramp)',
    'w.costas_b_not_found': 'Costas B not found',
    'w.fec_bits': 'FEC Bits',
    'w.result': 'Result',
    'w.partial': 'Partial',
    'w.ok2': 'OK',
    'w.margin': 'Margin',
    'w.message': 'Message',
    'w.macro_name': 'Macro Name',
    'w.macro_text': 'Macro Text',
    'w.mycall_dxcall_snr_allowed': '{MYCALL} {DXCALL} {SNR} allowed',
    'w.evm_1f_db_before': 'EVM {:.1f} dB (before EQ {:.1f} dB)',
    'w.residual_drift_2f_hz': 'Residual drift {:+.2f} Hz',
    'w.no_eq_decode_failed': 'No EQ (decode failed) · raw shown',
    'w.no_phase_reference_old': 'No phase reference (old format)',
    'w.frame_highlighted': 'Frame {} highlighted',
    'w.live': 'Live',
    'w.last_1_5_s': 'Last 1.5 s (0 = now)',
    'w.snapshot': 'Snapshot',
    'w.detection_snapshot_map_at': 'Detection snapshot: map at last Costas A detection (0 = detected window)',
    'w.nn_features': 'NN Features',
    'w.2d_pca_of_rx': '2D PCA of RX NN features before decision',
    'w.phase_trace': 'Phase Trace',
    'w.eq_i_q_trace': 'EQ I/Q trace of selected frame',
    'qso.stop_first_bytes': ' · Stop: first {} / {} bytes',
    'qso.tx_stage': 'TX Stage',
    'qso.current_seg': 'Current Seg',
    'qso.elapsed': 'Elapsed',
    'qso.remaining3': 'Remaining',
    'qso.throughput_data': 'Throughput Data',
    'qso.throughput_total': 'Throughput Total',
    'qso.seg_text': 'Seg Text',
    'qso.seg_bytes': 'Seg Bytes',
    'qso.chars_in_sent_segments': 'Chars in sent segments ÷ time since first data frame\nCounted when a segment is fully sent',
    'qso.chars_in_sent_segments2': 'Chars in sent segments ÷ time since TX start (silence · tone · Costas A included)',
    'qso.bytes_32_seg_2': '① Bytes (32 seg + 2 CRC16)',
    'qso.info_bits': '② Info Bits',
    'qso.convolutional_code_bits_k': '③ Convolutional Code Bits (K=7, R=1/2)',
    'qso.tx_position_after_interleaving': '④ TX Position after Interleaving',
    'qso.lead_silence': 'Lead silence',
    'qso.tone_300_ms': 'Tone (300 ms)',
    'qso.start_sync_welch12_costas': 'Start sync (Welch12 Costas)',
    'qso.guard_frame_start': 'Guard frame (start)',
    'qso.mid_sync_m': 'Mid sync M{}',
    'qso.data_frame2': 'Data frame {} / {}',
    'qso.guard_frame_end': 'Guard frame (end)',
    'qso.costas_b_0_34': 'Costas B (0.34 s)',
    'qso.tail_silence': 'Tail silence',
    'qso.costas_a': 'Costas A',
    'qso.costas_b': 'Costas B',
    'qso.sending_done': 'Sending {} / {} (done {})',
    'qso.none_seg_sent': 'None · {} seg sent',
    'qso.idle_seg_total': 'Idle · {} seg total',
    'qso.stop_up_to_seg': ' · Stop: up to seg {}',
    'qso.length_b': '(length {} B) ',
    'qso.drift': 'Drift',
    'qso.resync': 'Resync',
    'qso.message_reason': 'Message · Reason',
    't1.first_block': 'First block',
    't1.next_block': 'Next block',
    't1.combined_x': 'Combined {}x',
    't1.single_decode': 'Single decode',
    't1.14_padding_partial_code': '{:<14} padding (partial code, dropped)',
    't1.no_rx_packet': 'No RX packet',
    't1.x_combined': ' · {}x combined',
    't1.padding_bits_1': 'Padding {} bits (1)',
    'frag.encode_bytes_differs_from': 'encode_bytes differs from encode_stream',
    'frag.block_of_a_past': 'Block of a past message decoded late by repeat combining',
    'frag.tng5_start_sync_welch': 'TNG5 start sync Welch 12 Costas',
    'frag.per_segment_18_bytes': 'per segment 18 bytes + CRC16 + tail 6',
    'frag.turns_confirmed_when_a': 'turns confirmed when a block passes CRC16',
    'frag.stop_message_does_not': 'stop message does not match frames already sent',
    'frag.per_segment_160_tail': 'per segment 160 + tail 6 + pad 2',
    'frag.tng5_message_end_from': 'TNG5 message end from length field',
    'frag.same_band_inside_a': 'same band inside a finished message',
    'frag.install_hamlib_or_set': 'install Hamlib or set its path',
    'frag.m_join_hypothesis_passed': 'M join hypothesis passed CRC first',
    'frag.charset1_57_chars_variable': 'charset1 57 chars variable length',
    'frag.bytes_18_crc16_2': '① Bytes 18 + CRC16 2',
    'frag.generators_117_127_155': 'generators 117 127 155 171',
    'frag.code_bits_after_deinterleaving': 'code bits after deinterleaving',
    'frag.corrections_on_checkable_bits': 'corrections on checkable bits',
    'frag.ptt_release_sent_on': 'PTT release sent on reconnect',
    'frag.12_sync_80_data': '12 sync + 80 data symbols',
    'frag.not_found_within_expected': 'not found within expected end + 2 s',
    'frag.deinterleave_combine_4_repeats': 'deinterleave + combine 4 repeats',
    'frag.updated_on_each_block': 'updated on each block CRC16 OK',
    'frag.tone_300_ms_costas': 'tone 300 ms + Costas A',
    'frag.same_band_inside_a2': 'same band inside a confirmed message',
    'frag.crc16_per_18_byte': 'CRC16 per 18-byte segment',
    'frag.mid_sync_m_every': 'mid sync M every 20 frames',
    'frag.crc16_per_32_byte': 'CRC16 per 32-byte segment',
    'frag.tng5_costas_a_not': 'TNG5 Costas A not found',
    'frag.tng5_costas_b_1': 'TNG5 Costas B × 1',
    'frag.segment_end_48_info': 'segment end + 48 info bits',
    'frag.final_decode_after_b': 'final decode after B runs to the end',
    'frag.tng5_mid_sync_not': 'TNG5 mid sync not found',
    'frag.tng5_costas_b_ignored': 'TNG5 Costas B ignored',
    'frag.tng5_costas_b_confirmed': 'TNG5 Costas B confirmed',
    'frag.charset1_variable_length': 'charset1 variable length',
    'frag.length_field_costas_b': 'length field + Costas B',
    'frag.switched_to_pending_a': 'switched to pending A',
    'frag.full_range_after_2': 'full range after 2 fails',
    'frag.for_large_or_dual': 'for large or dual screens',
    'frag.one_crc16_for_the': 'one CRC16 for the packet',
    'frag.removed_quietly_if_not': 'removed quietly if not confirmed',
    'frag.664_bits_4_repeats': '664 bits × 4 repeats',
    'frag.ptt_method_cat_unavailable': 'PTT method CAT unavailable',
    'frag.tng5_message_end_detected': 'TNG5 message end detected',
    'frag.link7_streaming_v2': 'link7 streaming v2',
    'frag.rigctld_start_failed': 'rigctld start failed',
    'frag.rigctld_connection_lost': 'rigctld connection lost',
    'frag.rigctld_connect_failed': 'rigctld connect failed',
    'frag.code_bit_tx_position': '④ Code bit TX position',
    'frag.guard_frame_192_ms': 'guard frame 192 ms',
    'frag.random_within_segment_delay': 'random within segment + delay',
    'frag.accepted_after_length_field': 'accepted after length field result',
    'frag.replaced_by_final_result': 'replaced by final result when done',
    'frag.switched_to_stronger_new': 'switched to stronger new A',
    'frag.code_bits_after_deinterleaving2': 'code bits after deinterleaving',
    'frag.start_sync_welch12': 'start sync Welch12',
    'frag.mid_sync_check_had': 'mid sync check had failed',
    'frag.costas_a_224_ms': 'Costas A 224 ms',
    'frag.costas_b_224_ms': 'Costas B 224 ms',
    'frag.ptt_port_open_failed': 'PTT port open failed',
    'frag.tng1_block_rx': 'TNG1 block RX',
    'frag.tng5_mid_sync_m': 'TNG5 mid sync M',
    'frag.length_field_not_decoded': 'length field not decoded',
    'frag.viterbi_output_info_bits': 'Viterbi output info bits',
    'frag.bits_in_frames_f': 'bits in frames F',
    'frag.not_opened_as_new': 'not opened as new message',
    'frag.rx_nn_output_llr': 'RX NN output LLR',
    'frag.interleaver_about_9_6': 'interleaver about 9.6 s',
    'frag.mid_sync_remeasure_failed': 'mid sync remeasure failed',
    'frag.4_codewords_664_bits': '4 codewords 664 bits',
    'frag.frequency_differs_from_a': 'frequency differs from A',
    'frag.crc16_fail_segment': 'CRC16 fail segment',
    'frag.tng5_unconfirmed_dropped': 'TNG5 unconfirmed dropped',
    'frag.tng5_costas_b': 'TNG5 Costas B',
    'frag.tng5_not_enough_frames': 'TNG5 not enough frames',
    'frag.rigctld_exited': 'rigctld exited',
    'frag.mean_per_repeat_copy': '③ Mean per repeat copy',
    'frag.not_at_segment_boundary': 'not at segment boundary',
    'frag.from_length_field_end': 'from length field end',
    'frag.top_sync_accumulation_candidate': 'top sync accumulation candidate',
    'frag.sum_of_4_copy': 'sum of 4 copy LLRs',
    'frag.grid_of_message_in': 'grid of message in RX',
    'frag.searching_back': 'searching back…',
    'frag.interleaver_3_2_s': 'interleaver ±3.2 s',
    'frag.mid_sync_m1_confirmed': 'mid sync M1 confirmed',
    'frag.waiting_for_mid_sync': 'waiting for mid sync',
    'frag.mid_sync_check_failed': 'mid sync check failed',
    'frag.max_tx_time_exceeded': 'max TX time exceeded',
    'frag.max_shift_3_2': 'max shift 3.2 s',
    'frag.lead_tone_300_ms': 'lead tone 300 ms',
    'frag.5_combine_4_repeats': '5 combine 4 repeats',
    'frag.7_segment_crc16': '7 segment CRC16',
    'frag.7_costas_array': '7 Costas array',
    'frag.cat_not_connected': 'CAT not connected',
    'frag.tng1_rx_error': 'TNG1 RX error',
    'frag.tng5_v1_file': 'TNG5 v1 file',
    'frag.tng5_message_end': 'TNG5 message end',
    'frag.tng5_rx_error': 'TNG5 RX error',
    'frag.tng5_rx_confirmed': 'TNG5 RX confirmed',
    'frag.tng5_signal_detected': 'TNG5 signal detected',
    'frag.tng5_signal_lost': 'TNG5 signal lost',
    'frag.tng5_packet_anatomy': 'TNG5 Packet Anatomy',
    'frag.tng5_join_failed': 'TNG5 join failed',
    'frag.hard_errors': 'hard errors',
    'frag.rigctld_not_found': 'rigctld not found',
    'frag.whole_chars_per_segment': 'whole chars per segment',
    'frag.false_b_in_data': 'false B in data',
    'frag.eot_in_last_segment': 'EOT in last segment',
    'frag.decode_received_part': 'decode received part',
    'frag.differs_from_strongest': 'differs from strongest',
    'frag.mid_sync_gaps_included': 'mid sync gaps included',
    'frag.confirmed_by_first_crc': 'confirmed by first CRC',
    'frag.up_to_about_9': 'up to about 9.6 s',
    'frag.costas_a_false_detect': 'Costas A false detect',
    'frag.costas_b_backward': 'Costas B backward',
    'frag.clock_drift_estimate': 'clock drift estimate',
    'frag.error_bits_per_frame': 'error bits per frame',
    'frag.every_3_84_s': 'every 3.84 s',
    'frag.signal_continues_after_b': 'signal continues after B',
    'frag.crc_ok_blocks': 'CRC OK blocks',
    'frag.no_crc_ok': 'no CRC OK',
    'frag.ptt_button_pressed': 'PTT button pressed',
    'frag.ptt_released_automatically': 'PTT released automatically',
    'frag.ptt_test': 'PTT test',
    'frag.no_ptt_port': 'no PTT port',
    'frag.first_2_bytes_of': 'first 2 bytes of S1',
    'frag.tng1_rx': 'TNG1 RX',
    'frag.tng1_streaming': 'TNG1 streaming',
    'frag.seg_not_received': 'seg not received',
    'frag.mean_per_repeat_copy2': 'mean per repeat copy',
    'frag.no_live_confirm': 'no live confirm',
    'frag.no_backward_decode': 'no backward decode',
    'frag.tx_halted_by_error': 'TX halted by error',
    'frag.expert_panels_hidden': 'expert panels hidden',
    'frag.corrected_code_bits': 'corrected code bits',
    'frag.costas_b_confirmed': 'Costas B confirmed',
    'frag.2_byte_value_v': '2-byte value v',
    'frag.crc16_fail': 'CRC16 fail',
    'frag.crc16_ok': 'CRC16 OK',
    'frag.m1_check_failed': 'M1 check failed',
    'frag.combined_code_bits': 'combined code bits',
    'frag.using_default_device': 'using default device',
    'frag.from_length_field_end2': 'from length field end',
    'frag.rest_padded_with_1': 'rest padded with 1',
    'frag.next_signal_started': 'next signal started',
    'frag.single_block_format': 'single block format',
    'frag.to_pending_a': 'to pending A',
    'frag.outside_data': 'outside data',
    'frag.message_rx': 'message RX',
    'frag.some_blocks_failed': 'some blocks failed',
    'frag.tx_stop_done': 'TX stop done',
    'frag.tx_halted': 'TX halted',
    'frag.rx_message_table': 'RX message table',
    'frag.rx_raw_waveform': 'RX raw waveform',
    'frag.message_in_rx': 'message in RX',
    'frag.rx_confirm_path': 'RX confirm path',
    'frag.start_sync_score': 'start sync score',
    'frag.saved_device_missing': 'saved device missing',
    'frag.corrected_code_bits2': 'corrected code bits',
    'frag.traceback_48': 'traceback 48',
    'frag.after_freq_correction': 'after freq correction',
    'frag.mid_sync_join': 'mid sync join',
    'frag.delay_unit_24': 'delay unit 24',
    'frag.first_crc_rescue': 'first CRC rescue',
    'frag.no_first_crc': 'no first CRC',
    'frag.first_crc_ok': 'first CRC OK',
    'frag.max_length_exceeded': 'max length exceeded',
    'frag.costas_a_b': 'Costas A+B',
    'frag.costas_a_4': 'Costas A×4',
    'frag.select_a_packet': 'select a packet',
    'frag.frame_count_fixed': 'frame count fixed',
    'frag.no_anatomy_data': 'no anatomy data',
    'frag.not_shown': 'not shown',
    'frag.5_deinterleave': '5 deinterleave',
    'frag.tng1_detected': 'TNG1 detected',
    'frag.tng1_block': 'TNG1 block',
    'frag.tng1_tx': 'TNG1 TX',
    'frag.tng1_signal': 'TNG1 signal',
    'frag.tng5_seg': 'TNG5 seg',
    'frag.char_codes': '② Char codes',
    'frag.r1_per_segment': 'R1 per segment',
    'frag.end_chars_cut': 'end chars cut',
    'frag.no_end_mark': 'no end mark',
    'frag.data_frame': 'data frame',
    'frag.missed_seg': 'missed seg',
    'frag.byte_whitening': 'byte whitening',
    'frag.code_bits': 'code bits',
    'frag.shape_d': 'shape D',
    'frag.streaming_format': 'streaming format',
    'frag.start_missed': 'start missed',
    'frag.info_bits': 'info bits',
    'frag.mid_sync_m': 'mid sync M',
    'frag.before_first_crc': 'before first CRC',
    'frag.first_mid_sync': 'first mid sync',
    'frag.click_a_layer': 'click a layer',
    'frag.errors_per_frame': 'errors per frame',
    'frag.mean_per_frame': 'mean per frame',
    'frag.tentative_display': 'tentative display',
    'frag.2_baseband': '2 baseband',
    'frag.2656_bits': '2656 bits',
    'frag.agc_settle': 'AGC settle',
    'frag.a_b_interval': 'A~B interval',
    'frag.cat_lost': 'CAT lost',
    'frag.no_cat': 'No CAT',
    'frag.crc_fail': 'CRC fail',
    'frag.no_crc': 'no CRC',
    'frag.crc_ok': 'CRC OK',
    'frag.ptt_failed': 'PTT failed',
    'frag.18_samples': '±18 samples',
    'frag.interleaver': '④ Interleaver',
    'frag.computed_crc': 'computed CRC',
    'frag.baseband_i': 'baseband I',
    'frag.resend': 'Resend',
    'frag.unconfirmed_signal': 'unconfirmed signal',
    'frag.codeword_order': 'codeword order',
    'frag.viterbi_input': 'Viterbi input',
    'frag.t_r_switch': 'T/R switch',
    'frag.tx_monitor': 'TX Monitor',
    'frag.false_detect_dropped': 'false detect dropped',
    'frag.all_bytes': 'all bytes',
    'frag.freq_error': 'freq error',
    'frag.sorted_by_delay': 'sorted by delay',
    'frag.snr_est': 'SNR Est',
    'frag.costas_a': 'Costas A',
    'frag.costas_b': 'Costas B',
    'frag.white_border': 'white border',
    'frag.not_shown2': 'not shown',
    'frag.1_audio': '1 audio',
    'frag.20_frames': '20 frames',
    'frag.stages_4_6': 'stages 4~6',
    'frag.6_viterbi': '6 Viterbi',
    'frag.8_bytes': '8 bytes',
    'frag.a_not_found': 'A not found',
    'frag.b_not_found': 'B not found',
    'frag.b_only': 'B only',
    'frag.m1_confirmed': 'M1 confirmed',
    'frag.v1_file': 'v1 file',
    'frag.branch_12': 'branch 12',
    'frag.decision_depth': 'decision depth',
    'frag.seg_decoded': 'seg decoded',
    'frag.length_field': 'length field',
    'frag.late_combine': 'late combine',
    'frag.next_signal': 'next signal',
    'frag.single_block': 'single block',
    'frag.message_end': 'message end',
    'frag.nothing_decoded': 'nothing decoded',
    'frag.decode_ok': 'decode OK',
    'frag.decode_failed': 'decode failed',
    'frag.decoding': 'decoding…',
    'frag.partial': 'Partial',
    'frag.code_bits2': 'code bits',
    'frag.block_ok': 'block OK',
    'frag.per_copy': 'per copy',
    'frag.selected_packet': 'selected packet',
    'frag.tx_order': 'TX order',
    'frag.tx_start': 'TX start',
    'frag.tx_done': 'TX done',
    'frag.tx_position': 'TX position',
    'frag.tx_halted2': 'TX halted',
    'frag.tx_focus': 'TX focus',
    'frag.tx_stopped': 'TX stopped',
    'frag.tx_anatomy': 'TX Anatomy',
    'frag.stopped': 'stopped',
    'frag.rx_log': 'RX Log',
    'frag.rx_confirmed': 'RX confirmed',
    'frag.start_sync': 'start sync',
    'frag.signal_lost': 'signal lost',
    'frag.complete': 'Complete',
    'frag.no_response': 'no response',
    'frag.no_data': 'no data',
    'frag.relock': 'relock',
    'frag.no_device': 'no device',
    'frag.show_all': 'show all',
    'frag.connect_failed': 'connect failed',
    'frag.alignment_hypothesis': 'alignment hypothesis',
    'frag.info_bits2': 'info bits',
    'frag.fixed_bits': 'fixed bits',
    'frag.mid_sync': 'mid sync',
    'frag.max_level': 'max level',
    'frag.final_decision': 'final decision',
    'frag.track_4': 'track ±4',
    'frag.file_decode': 'file decode',
    'frag.no_packet': 'no packet',
    'frag.frame_f': 'frame F',
    'frag.frame_color': 'frame color',
    'frag.format_mark': 'format mark',
    'frag.checkable': 'checkable',
    'frag.waiting_for_check': 'waiting for check',
    'frag.check_failed': 'check failed',
    'frag.check_ok': 'check OK',
    'frag.candidate_dropped': 'candidate dropped',
    'frag.failed': "' failed",
    'frag.hex': 'hex',
    'frag.3_seg': '3 seg',
    'frag.8_chars': '8 chars',
    'frag.no_a': 'no A',
    'frag.b_missing': 'B missing',
    'frag.no_b': 'no B',
    'frag.s_off': 's off',
    'frag.computed': '≠ computed',
    'frag.code': '③ Code',
    'frag.after_combining': 'after combining',
    'frag.seg_s': 'seg S',
    'frag.chars': 'chars',
    'frag.tail_6': 'tail 6',
    'frag.end_mark': 'end mark',
    'frag.sync_z': 'sync z',
    'frag.sync_map': 'sync map',
    'frag.sync_cells': 'sync cells',
    'frag.drift': 'drift',
    'frag.only_detected': 'only detected',
    'frag.repeat_4': 'repeat 4',
    'frag.bits': 'bits',
    'frag.selected_layer': 'selected layer',
    'frag.tx': 'TX',
    'frag.rx': 'RX',
    'frag.streaming': 'streaming',
    'frag.interleaver2': 'interleaver',
    'frag.info_cells': 'info cells',
    'frag.to_start': 'To Start',
    'frag.tone_start': 'tone start',
    'frag.x_combined': 'x combined',
    'frag.hex2': 'hex',
    'frag.19': '19',
    'frag.3_chars': '3 chars',
    'frag.7_stages': '7 stages',
    'frag.after_a': 'after A',
    'frag.data': 'data',
    'frag.macro': 'macro',
    'frag.not_found': 'not found',
    'frag.unconfirmed': 'unconfirmed',
    'frag.pending': 'pending',
    'frag.bytes': 'bytes',
    'frag.constellation': 'constellation',
    'frag.live': 'live',
    'frag.backward': 'backward',
    'frag.connected': 'connected',
    'frag.audio': 'audio',
    'frag.waterfall': 'waterfall',
    'frag.reuse': 'reuse',
    'frag.resync': 'resync',
    'frag.exited': 'exited',
    'frag.freq': 'freq',
    'frag.reset': 'reset',
    'frag.text': 'text',
    'frag.frame': 'frame',
    'frag.guard': 'guard',
    'frag.virtual': 'virtual',
    'frag.detected': 'detected',
    'frag.each': 'each',
    'frag.detected2': 'detected',
    'frag.result': 'result',
    'frag.combined': 'combined',
    'frag.path': 'path',
    'frag.computed2': 'computed',
    'frag.seg': 'seg',
    'frag.chars2': 'chars',
    'frag.ref': 'ref',
    'frag.symbol': 'symbol',
    'frag.length': 'length',
    'frag.text2': 'text',
    'frag.slow': 'Slow',
    'frag.next': 'Next',
    'frag.similarity': 'similarity',
    'frag.waiting': 'waiting',
    'frag.sync': 'sync',
    'frag.registered': 'registered',
    'frag.mode': 'mode',
    'frag.unknown': 'unknown',
    'frag.group': 'group',
    'frag.threshold': 'threshold',
    'frag.normal': 'Normal',
    'frag.decode': 'decode',
    'frag.body': 'body',
    'frag.code2': 'code',
    'frag.analysis': 'Analysis',
    'frag.block': 'block',
    'frag.bits2': 'bits',
    'frag.fast': 'Fast',
    'frag.copy': 'copy',
    'frag.state': 'state',
    'frag.select': 'select',
    'frag.ok': 'OK',
    'frag.lost': 'lost',
    'frag.tx2': 'TX',
    'frag.rx2': 'RX',
    'frag.time': 'time',
    'frag.time2': 'time',
    'frag.start': 'start',
    'frag.fail': 'fail',
    'frag.eye': 'eye',
    'frag.none': 'none',
    'frag.error': 'error',
    'frag.operate': 'Operate',
    'frag.position': 'position',
    'frag.prev': 'Prev',
    'frag.after': 'after',
    'frag.general': 'General',
    'frag.input': 'input',
    'frag.all': 'All',
    'frag.alignment': 'alignment',
    'frag.fixed': 'fixed',
    'frag.kind': 'kind',
    'frag.stop': 'stop',
    'frag.teal': 'teal',
    'frag.trend': 'trend',
    'frag.output': 'output',
    'frag.code3': 'code',
    'frag.ok2': 'OK',
    'frag.file': 'file',
    'frag.padding': 'padding',
    'frag.packet': 'packet',
    'frag.mean': 'mean',
    'frag.display': 'display',
    'frag.join': 'join',
    'frag.item': 'item',
    'frag.format': 'format',
    'frag.confirmed': 'confirmed',
    'frag.value': 'value',
    'frag.x': '',
    'frag.x2': '',
    'frag.first': 'first',
    'frag.chars3': 'chars',
    'frag.layer': 'layer',
    'frag.tone': 'tone',
    'frag.x3': 'x',
    'main.error_prefix': 'Error: ',
    'main.local_suffix': ' Local',
    'zoom.res.시간 우선 (4Hz)': 'Time (4 Hz)',
    'zoom.res.균형 (2Hz)': 'Balanced (2 Hz)',
    'zoom.res.주파수 우선 (1Hz)': 'Frequency (1 Hz)',
    'dis.prev': 'Prev',
    'dis.next': 'Next',
    'dis.to_start': 'To Start',
    'dis5.col.seg': 'Seg',
    'dis5.col.chars': 'Chars',
    'dis5.col.frames': 'Frames',
    'dis5.col.llr': 'LLR\\||Mean \\|LLR\\|',
    'dis5.col.fixed': 'Fixed',
    'dis5.col.hex': 'Bytes (hex)',
    'dis5.col.text': 'Text',
    'setup.title': 'Setup',
    'setup.step.lang': 'Language',
    'setup.step.call': 'Call Sign',
    'setup.step.audio': 'Audio',
    'setup.step.radio': 'Radio',
    'setup.step.diag': 'Diagnostics',
    'setup.step.done': 'Done',
    'setup.hint.lang': 'You can change this at any time in Settings.',
    'setup.hint.call': 'This call sign is used for {MYCALL} in macros.',
    'setup.hint.audio': 'Select the input and output devices connected to your radio.',
    'setup.hint.radio': 'To continue without a radio, click Skip. You can connect a radio later in the Radio tab of Settings.',
    'setup.hint.diag': "Checks whether this PC's CPU and audio devices are suitable for running TNG PKT. This takes about 30 seconds.",
    'setup.hint.done': 'Setup is complete. Click Start to launch TNG PKT.',
    'setup.prev': 'Back',
    'setup.next': 'Next',
    'setup.skip': 'Skip',
    'setup.finish': 'Start',
    'setup.test_tone': 'Test Tone',
    'setup.call': 'My Call',
    'diag.title': 'Diagnostics',
    'diag.run': 'Run Diagnostics',
    'diag.running': 'Checking',
    'diag.none': 'No result',
    'diag.cpu': 'CPU',
    'diag.cpu_error': 'Check error: {}',
    'diag.cpu_margin': 'Processing margin {:.1f}x · {:.1f}x on 1 core',
    'diag.no_open': 'Failed to open device: {}',
    'diag.fs': '{:.0f} Hz',
    'diag.xrun': '{} buffer dropouts',
    'diag.ppm': 'Clock error {:+.0f} ppm (±{:.0f})',
    'diag.ok': 'Pass',
    'diag.warn': 'Warning',
    'diag.bad': 'Fail',
    'diag.time': 'Checked: {}',
    'diag.failed': 'Diagnostics could not be completed: {}',
    'set.setup_group': 'Setup',
    'set.rerun_setup': 'Run Setup Again',
    'set.rerun_diag': 'Run Diagnostics',
    'macro.reply': 'Reply',
    'macro.report': 'Report',
    'diag.step.start': 'Preparing',
    'diag.step.audio': 'Checking audio devices',
    'diag.step.load': 'Loading receiver models',
    'diag.step.mode': 'Checking {} receive processing',
    'diag.step.mode1': 'Checking {} receive processing (1 core)',
    'diag.step.done': 'Complete',
    'diag.cpu_margin1': 'Processing margin {:.1f}x (1 core)',
}
